.net core 8 mvc/FetchNewsProject/FetchNewsProject/Models/DbContext.cs
using Microsoft.EntityFrameworkCore;
using FetchNewsProject.Models;

namespace FetchNewsProject.Data
{
    public class NewsContext : DbContext
    {
        public NewsContext(DbContextOptions<NewsContext> options) : base(options)
        {
        }

        public DbSet<NewsItem> NewsItems { get; set; }
    }
}

.net core 8 mvc/FetchNewsProject/FetchNewsProject/Models/ErrorViewModel.cs
namespace FetchNewsProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

.net core 8 mvc/FetchNewsProject/FetchNewsProject/Models/NewsItem.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FetchNewsProject.Models
{
    public class NewsItem
    {
        [Key]
        public int Id { get; set; }
        public string? Source { get; set; }
        public DateTime? Date { get; set; }
        [Display(Name = "Formatted Date")]
        public string? FormattedDate => Date?.ToString("yyyy-MM-dd");
        public string? Title { get; set; }
        public string? Summary { get; set; }
        public string? Link { get; set; }
        [Display(Name = "Image")]
        public string? ImageData { get; set; }
        public string? SearchQuery { get; set; }
    }
}

.net core 8 mvc/FetchNewsProject/FetchNewsProject/Controllers/NewsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic; // 如果要接收一個列表的數據
using FetchNewsProject.Models;
using FetchNewsProject.Data;

namespace FetchNewsProject.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class NewsController : ControllerBase
    {
        private readonly NewsContext _context;

        public NewsController(NewsContext context)
        {
            _context = context;
        }

        [HttpPost]
        public IActionResult Post([FromBody] List<NewsItem> newsItems)
        {
            if (newsItems == null || newsItems.Count == 0)
            {
                return BadRequest("No news items provided.");
            }

            _context.NewsItems.AddRange(newsItems);
            _context.SaveChanges();

            return Ok("Data saved to database successfully!");
        }
        [HttpDelete("clear")]
        public IActionResult ClearNewsItems()
        {
            try
            {
                // ToList() 確保查詢立即執行，這樣可以避免在操作中持有開啟的 DataReader
                var newsItems = _context.NewsItems.ToList();
                if (newsItems.Any())
                {
                    _context.NewsItems.RemoveRange(newsItems);
                    _context.SaveChanges();
                    return Ok("All news items have been deleted.");
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, "An error occurred while clearing news items.");
            }

            return NoContent(); // 當沒有內容需要刪除時返回
        }
    }
}

.net core 8 mvc/FetchNewsProject/FetchNewsProject/Controllers/NewsViewController.cs
using Microsoft.AspNetCore.Mvc;
using FetchNewsProject.Models;
using System.Collections.Generic;
using Microsoft.Extensions.Logging;
using FetchNewsProject.Data;
using System.Linq;

namespace FetchNewsProject.Controllers
{
    public class NewsViewController : Controller
    {
        private readonly NewsContext _context;
        private readonly ILogger<NewsViewController> _logger;

        public NewsViewController(ILogger<NewsViewController> logger, NewsContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index(string source, string searchQueryInput, string fromDate, string toDate)
        {
            try
            {
                var query = _context.NewsItems.AsQueryable();
                
                if (query == null) 
                {
                    return NotFound();
                }

                if (!string.IsNullOrEmpty(source))
                {
                    query = query.Where(n => n.Source == source);
                }
                if (!string.IsNullOrEmpty(searchQueryInput))
                {
                    query = query.Where(n => n.Title.Contains(searchQueryInput) || n.Summary.Contains(searchQueryInput));
                }

                // Parse the fromDate and toDate
                if (DateTime.TryParse(fromDate, out DateTime parsedFromDate))
                {
                    query = query.Where(n => n.Date >= parsedFromDate);
                }
                if (DateTime.TryParse(toDate, out DateTime parsedToDate))
                {
                    query = query.Where(n => n.Date <= parsedToDate);
                }

                var newsItems = query.OrderByDescending(n => n.Date ?? DateTime.MinValue).ToList();
                var sources = _context.NewsItems.Select(n => n.Source).Distinct().ToList();
                var searchQuery = _context.NewsItems.Select(n => n.SearchQuery).Distinct().ToList();

                ViewBag.Sources = sources;
                ViewBag.CurrentSource = source;
                ViewBag.SearchWord = searchQueryInput;
                ViewBag.SearchQuery = searchQuery;

                return View(newsItems);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to load news items.");
                return View("Error");
            }
        }
    }
}

.net core 8 mvc/FetchNewsProject/FetchNewsProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

.net core 8 mvc/FetchNewsProject/FetchNewsProject/Views/NewsView/Index.cshtml
@model IEnumerable<FetchNewsProject.Models.NewsItem>

@{
    ViewData["Title"] = "Index";
    var sources = ViewBag.Sources as List<string>;
    var currentSource = ViewBag.CurrentSource as string;
    var currentSearchWord = ViewBag.SearchWord as string;
    var searchQuery = ViewBag.SearchQuery as List<string>;
}

<link rel="stylesheet" href="~/css/site.css">
@* <script src="~/lib/jquery/dist/jquery.js"/></script> *@

<h1>Welcome</h1>
<h2>Topic: @(searchQuery != null ? string.Join(", ", searchQuery).ToLower() : "")</h2>
<form method="get" action="@Url.Action("Index", "NewsView")" class="form-inline">
    <div class="container">
        <div class="row">
            <div class="form-group col">
                <label for="sourceSelect" class="mr-1">Source:</label>
                <select class="form-control" id="sourceSelect" name="source">
                    <option value="">All Sources</option>
                    @if (sources != null)
                    {
                        @foreach (var source in sources)
                        {
                            <option value="@source">@source</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group col">
                <label for="fromDate" class="mr-1">From:</label>
                @* <input type="text" class="form-control datepicker" id="fromDate" name="fromDate"> *@
                <input type="date" id="fromDate" name="fromDate" class="form-control datepicker" />
            </div>
            <div class="form-group col">
                <label for="toDate" class="mr-1">To:</label>
                @* <input type="text" class="form-control datepicker" id="toDate" name="toDate"> *@
                <input type="date" id="toDate" name="toDate" class="form-control datepicker" />
            </div>
        </div>
        <div class="row">
            <div class="form-group mr-2">
                <label for="searchQuery" class="mr-1">Search:</label>
                <input type="text" class="form-control" id="searchQueryInput" name="searchQueryInput" value="@currentSearchWord" />
            </div>
        </div>
        <button type="submit" class="btn btn-success mr-1">Filter</button>
        <button type="button" class="btn btn-danger" onclick="clearFilters()">Clear</button>
    </div>   
 
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Source)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageData)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Summary)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if(Model != null){
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Source)
                    </td>
                    <td class="nowrap">
                        @Html.DisplayFor(modelItem => item.FormattedDate)
                    </td>
                    <td>
                        @if (!string.IsNullOrEmpty(item.ImageData))
                        {
                            <img src="data:image/jpeg;base64,@item.ImageData" alt="News Image" style="width:100px;">
                        }
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Summary)
                    </td>
                    <td>
                        <a href="@item.Link" target="_blank" class="btn btn-primary">More</a>
                    </td>
                </tr>
             }
        }
    </tbody>
</table>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script>
        // $(function () {
        //     $(".datepicker").datepicker({
        //         dateFormat: 'yy-mm-dd'
        //     });
        // });

        function clearFilters() {
            $('#sourceSelect').val('');
            $('#searchQueryInput').val('');
            $('#fromDate').val('');
            $('#toDate').val('');            
            $('form').submit(); // 重新提交表单
            console.log("clearFilter!!");
        }
    </script>
}

.net core 8 mvc/FetchNewsProject/FetchNewsProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FetchNewsProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FetchNewsProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BIMFM NEWS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
@*                 <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div> *@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BIMFM NEWS
        </div>
    </footer>
    @* <script src="~/lib/jquery/dist/jquery.min.js"></script> *@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>